### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by sntgC** [sntgC/utfour#3]
After creating a user, I cannot sign in with that same user. However, the issue is fixed when I manually put in an id for the user through SQL. It seems as if the server code isn't generating an id and that causes problems when trying to sign in. For reference, my table is called 'users' and has 'id','username', and 'password' fields.

**Comment by CDogg99** [comment]
I have tested the system extensively on my WAMP server without experiencing any issues, so we'll need to collaborate in a Skype call to try and troubleshoot it.

**Comment by CDogg99** [comment]
Didn't mean to close. Oops
